### ISSUE TITLE
Error in compiling

### ISSUE THREAD

**Issue by 4Joe** [bbonev/eoip#11]
Got this error below while compiling.
my system is Ubuntu 18.04.5 LTS

dafi@fujitsu:~/linux-source-4.15.0/eoip/out-of-tree-4.15.x$ make
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-65-generic'
  CC [M]  /home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x/eoip.o
/home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x/eoip.c: In function ‘eoip_if_xmit’:
/home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x/eoip.c:485:3: error: too many arguments to function  skb_dst((const struct sk_buff *)skb)->ops->update_pmtu’
   skb_dst(skb)->ops->update_pmtu(skb_dst(skb), NULL, skb, mtu, true);
   ^~~~~~~
scripts/Makefile.build:337: recipe for target '/home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x/eoip.o' failed
make[2]: *** [/home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x/eoip.o] Error 1
Makefile:1571: recipe for target '_module_/home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x' failed
make[1]: *** [_module_/home/dafi/linux-source-4.15.0/eoip/out-of-tree-4.15.x] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-65-generic'
Makefile:11: recipe for target 'default' failed
make: *** [default] Error 2

**Comment by bbonev** [comment]
Hello,

In Ubuntu 18.04 there are kernels with the same version but different API.

The source is made for the latest update - upgrade your kernel and it will work.

As an alternative, you can change that line to:

`skb_dst(skb)->ops->update_pmtu(skb_dst(skb), NULL, skb, mtu);`

**Comment by 4Joe** [comment]
Great, update to latest kernel. Compiling was successful
