### ISSUE TITLE
Mainline?

### ISSUE THREAD

**Issue by Harvie** [bbonev/eoip#15]
Hello,
are there any chances of this getting merged into the mainline kernel?

**Comment by bbonev** [comment]
Nope, I have tried. Can't find the LKML reference now but the reject was definitive. Quoting by memory: "we have no intention to support a reverse engineered non-standard proprietary protocol".

On the other hand there is no standard alternative, the closest one is gretap but it is hard to make that carry 1500 mtu frames over a 1500 mtu network, also gretap does not support multiple tunnels between the same two endpoints.
