### ISSUE TITLE
patch error

### ISSUE THREAD

**Issue by zoigecyb** [bbonev/eoip#17]
file kernel-4.15.0-eoip-gre-demux.patch
reports "file to patch: "
tried on kernels 4.15.175, 4.19.237. Ubuntu 18.04.6

**Comment by bbonev** [comment]
Can you provide the full build log?

**Comment by zoigecyb** [comment]
patch: 
`/usr/src/linux-headers-4.19.237-0419237# patch -p1 < /home/aladm/eoip/kernel-patch/kernel-4.19.0-eoip-gre-demux.patch
patching file include/net/gre.h
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n] y
Hunk #1 succeeded at 31 with fuzz 2 (offset 22 lines).
can't find file to patch at input line 19
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- linux-3.15/net/ipv4/gre_demux.c.orig       2014-07-04 02:53:03.975398766 +0300
|+++ linux-3.15/net/ipv4/gre_demux.c    2014-06-16 00:10:05.118137863 +0300
--------------------------
File to patch:`

build ot of tree:
`~/eoip/out-of-tree-4.19.x# make
patching file eoip.c
using 4.19.0 version of gre_demux.c
found running kernel version of gre.h
patching file gre.h
Hunk #1 succeeded at 38 with fuzz 2 (offset 29 lines).
patching file gre_demux.c
Hunk #1 succeeded at 31 (offset 1 line).
Hunk #3 succeeded at 155 (offset -129 lines).
Hunk #4 succeeded at 191 (offset -129 lines).
make[1]: вход в каталог «/usr/src/linux-headers-4.19.237-0419237-generic»
  CC [M]  /home/aladm/eoip/out-of-tree-4.19.x/eoip.o
In file included from /home/aladm/eoip/out-of-tree-4.19.x/eoip.c:49:0:
./include/net/gre.h:31:0: warning: "GREPROTO_NONSTD_EOIP" redefined
 #define GREPROTO_NONSTD_EOIP       (0 + GREPROTO_NONSTD_BASE)

<command-line>:0:0: note: this is the location of the previous definition
In file included from /home/aladm/eoip/out-of-tree-4.19.x/eoip.c:49:0:
./include/net/gre.h:32:0: warning: "GREPROTO_NONSTD_MAX" redefined
 #define GREPROTO_NONSTD_MAX        (1 + GREPROTO_NONSTD_BASE)

<command-line>:0:0: note: this is the location of the previous definition
  CC [M]  /home/aladm/eoip/out-of-tree-4.19.x/gre.o
In file included from /home/aladm/eoip/out-of-tree-4.19.x/gre.c:27:0:
./include/net/gre.h:31:0: warning: "GREPROTO_NONSTD_EOIP" redefined
 #define GREPROTO_NONSTD_EOIP       (0 + GREPROTO_NONSTD_BASE)

<command-line>:0:0: note: this is the location of the previous definition
In file included from /home/aladm/eoip/out-of-tree-4.19.x/gre.c:27:0:
./include/net/gre.h:32:0: warning: "GREPROTO_NONSTD_MAX" redefined
 #define GREPROTO_NONSTD_MAX        (1 + GREPROTO_NONSTD_BASE)

<command-line>:0:0: note: this is the location of the previous definition
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /home/aladm/eoip/out-of-tree-4.19.x/eoip.mod.o
  LD [M]  /home/aladm/eoip/out-of-tree-4.19.x/eoip.ko
  CC      /home/aladm/eoip/out-of-tree-4.19.x/gre.mod.o
  LD [M]  /home/aladm/eoip/out-of-tree-4.19.x/gre.ko
make[1]: выход из каталога «/usr/src/linux-headers-4.19.237-0419237-generic»
root@psb-server:~/eoip/out-of-tree-4.19.x# insmod ./gre.ko
insmod: ERROR: could not insert module ./gre.ko: File exists
root@psb-server:~/eoip/out-of-tree-4.19.x# insmod ./eoip.ko
insmod: ERROR: could not insert module ./eoip.ko: Invalid parameters
root@psb-server:~/eoip/out-of-tree-4.19.x# ../eoip add name to_st local xxxx remote xxxx tunnel-id 124
RTNETLINK answers: Operation not supported
failed to talk to netlink!`
the last line of course predictible)

also tried on 4.15.175, 4.15.173 kernels. tried to compile 4.19.237 from sources.
when in /usr/src/linux-source-4.15.0 or in 4.19.237-0419237 output results are the same.

**Comment by bbonev** [comment]
Thanks for the report!

The first thing you are doing wrong is that you patch your kernel headers - patches in the kernel-patch folder and intended only in case you want to patch and build your own kernel. Patching linux-headers installed froma a package is harmful and unneeded. Reinstall your `linux-headers*` to fix that.

The second problematic part is that gre.ko is already loaded, `rmmod gre` first or else you will have an incompatible gre.ko loaded and `eoip` will not work.

Just follow these instructions (on a clean system):

````
cd path-to-eoip/out-of-tree-X.Y.Z
make
make install
````

**Comment by zoigecyb** [comment]
yes, you're right.
gre was loaded because i'm using gretap tunnel.
on clean system all is ok.
also stopped tunnels, ```rmmod gre``` and ```insmod gre.ko``` fixed problem.

but, while trying to make eoip, i rebuilt kernel and disabled many unneeded for me things on server that is used like router))

**Comment by bbonev** [comment]
Please read the documentation, it may be brief but this is there. The keepalive feature in MikroTik is not supported on the Linux side, so it needs to be disabled. Also it is a good idea to specify both local/remote addresses - MikroTik supports receiving packets in a tunnel from any remote address, while the Linux implementation does not.

You are missing `!keepalive`, also most probably mtu is wrong on the MikroTik...

````
/interface eoip add clamp-tcp-mss=no keepalive local-address=198.51.100.11 remote-address=203.0.113.50 tunnel-id=1234 mtu=1500 name=eoip1234
````

I am closing the issue, please reopen in case there is something to add to it or open a new one if you notice a different problem.
