### ISSUE TITLE
Missing linux/ip.h in include

### ISSUE THREAD

**Issue by Kun-Kun** [bbonev/eoip#19]
Version: `Linux server.com 5.4.188-1.el7.elrepo.x86_64 #1 SMP Mon Mar 28 09:10:07 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux`

gcc:
`Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,lto --prefix=/opt/rh/devtoolset-9/root/usr --mandir=/opt/rh/devtoolset-9/root/usr/share/man --infodir=/opt/rh/devtoolset-9/root/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --with-default-libstdcxx-abi=gcc4-compatible --enable-plugin --enable-initfini-array --with-isl=/builddir/build/BUILD/gcc-9.3.1-20200408/obj-x86_64-redhat-linux/isl-install --disable-libmpx --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 9.3.1 20200408 (Red Hat 9.3.1-2) (GCC) `

Problem:
When I start building  eoipcr an error is occured

`[root@server eoip]# make
CC eoipcr.o
In file included from eoipcr.c:7:
/usr/include/linux/if_tunnel.h:42:16: error: field ‘iph’ has incomplete type
   42 |  struct iphdr  iph;
      |                ^~~
make: *** [eoipcr.o] Error 1
`
How to fix:
Add include ip.h before if_tunnel.h
 #include <linux/ip.h>
#include <linux/if_tunnel.h>

Is it a problem in my version if_tunnel.h that is lack of include if ip.h or wrong include in eoipcr.c?
Maybe it is better to add including ip.h or write additional section in readme section with known issues&

**Comment by bbonev** [comment]
Is this a CentOS/RH 7?

Thanks for reporting that. I have applied your fix - it does not break newer systems.

**Comment by Kun-Kun** [comment]
Yes it is CentOS 7
