### ISSUE TITLE
openSUSE Leap 15.4: DKMS: "Invalid argument" when `modprobe`ing the installed module

### ISSUE THREAD

**Issue by maff1989** [bbonev/eoip#27]
![image](https://github.com/bbonev/eoip/assets/7083329/b0b2c4e4-b802-4732-909b-4a9845441e22)

```
# dkms status
eoip, 1.1, 5.14.21-150400.24.97-default, x86_64: installed
# modprobe eoip
modprobe: ERROR: could not insert 'eoip': Invalid argument
# dmesg | grep -i eoip
--snip--
[93971.853997] EoIP (IPv4) tunneling driver
[93971.854004] eoip init: can't add protocol
```

I'm able to build and install the latest commit using DKMS on a Raspberry Pi 4 B running Raspbian 11 kernel 6.1.21-v7l+

Any help is appreciated.

**Comment by maff1989** [comment]
I'm an idiot... Re-read your README and found the part about loading the proper `gre` module. I found that my running system still had the old `gre` loaded... unloaded that and `modprobe eoip` worked without error.

Sorry for the trouble!

**Comment by bbonev** [comment]
That was quick. Good luck
