### ISSUE TITLE
Install script will fail with bash -e

### ISSUE THREAD

**Issue by JKJameson** [bbonev/eoip#33]
Thanks for merging my PR.

I noticed you remove cat from the lines.

Just a heads up, without piping lsmod like this 
  `loaded=$(lsmod | grep '^gre ' | cat)`
the script will cease executing without an error message.

This is because bash is invoked with `#!/bin/bash -e` which will exit on error. As the output of the command is captured into a variable, nothing is shown in the output of the script.

**Comment by bbonev** [comment]
Oh, I didn't see the `-e`, that is why I changed it to `set -e`

Maybe the way to expand this is to ask and remove the `pptp` and/or `eoip` modules that may use the `gre` module. If there are configured and working eoip interfaces, they will disappear together with all the ips and routes.
