### ISSUE TITLE
RTNETLINK answers: Operation not permitted

### ISSUE THREAD

**Issue by normanx** [bbonev/eoip#9]
Hi,
I install a ubuntu 18.04 under VMWare and upgrade kernel to 4.19.128-0419128,  then I try to make eoip connection between my VPS and another RouterOS in VMWare, I use the command  "eoip add name testeoip local 192.168.17.12 remote 192.168.17.13 tunnel-id 6" on my ubuntu, and I got the response :
`RTNETLINK` answers: Operation not permitted
failed to talk to netlink!`
Does I need install some support libraries on my VPS or change any settings to make it working? Please help, Thank you very much!

**Comment by bbonev** [comment]
Add a `sudo` before the command

**Comment by normanx** [comment]
I use the root account execute the command, it not permissions issue.

**Comment by bbonev** [comment]
Normally when kernel modules are not loaded, or in case the standard `gre.ko` is loaded instead of the patched one, the error message will be:

```
RTNETLINK answers: Operation not supported
failed to talk to netlink!
```

I can not easily test with your combination of OS/kernel versions, here is the result with the default 18.04 ubuntu kernel:

```
root@ubuntu-18_04:~/eoip# make
cc -Wall -Os -c libnetlink.c
cc -Wall -Os -o eoip eoipcr.c libnetlink.o
strip eoip
root@ubuntu-18_04:~/eoip# cd out-of-tree-4.15.x/
root@ubuntu-18_04:~/eoip/out-of-tree-4.15.x# make
patching file eoip.c
using 4.15.0 version of gre_demux.c
found running kernel version of gre.h
patching file gre.h
Hunk #1 succeeded at 24 (offset 15 lines).
patching file gre_demux.c
Hunk #3 succeeded at 137 (offset -9 lines).
Hunk #4 succeeded at 173 (offset -9 lines).
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-106-generic'
  CC [M]  /root/eoip/out-of-tree-4.15.x/eoip.o
  CC [M]  /root/eoip/out-of-tree-4.15.x/gre.o
  Building modules, stage 2.
  MODPOST 2 modules
  CC      /root/eoip/out-of-tree-4.15.x/eoip.mod.o
  LD [M]  /root/eoip/out-of-tree-4.15.x/eoip.ko
  CC      /root/eoip/out-of-tree-4.15.x/gre.mod.o
  LD [M]  /root/eoip/out-of-tree-4.15.x/gre.ko
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-106-generic'
root@ubuntu-18_04:~/eoip/out-of-tree-4.15.x# insmod ./gre.ko
root@ubuntu-18_04:~/eoip/out-of-tree-4.15.x# insmod ./eoip.ko 
root@ubuntu-18_04:~/eoip/out-of-tree-4.15.x# ../eoip add name testeoip local 192.168.17.12 remote 192.168.17.13 tunnel-id 6
root@ubuntu-18_04:~/eoip/out-of-tree-4.15.x# ip li set testeoip up
```

**Comment by normanx** [comment]
Thank you very much! I have miss to load gre.ko module, after load the module, it gets worked.
